/**
 * The lab's audio manifest - the ONLY place that knows asset paths.
 * Files are generated by `npm run gen-audio` (scripts/gen-audio.mjs) into public/audio/.
 * Add a cue here (or bank.register() at runtime) and call it by id.
 */
import type { AudioCue } from './audioBank';

export const LAB_CUE = {
  ambience: 'ambience',
  command: 'command',
  success: 'success',
  fail: 'fail',
  trackLost: 'track_lost',
} as const;
export type LabCueId = (typeof LAB_CUE)[keyof typeof LAB_CUE];

export const LAB_CUES: AudioCue[] = [
  { id: LAB_CUE.ambience, src: 'audio/lab_drone_loop.wav', bus: 'ambience', loop: true, volume: 0.6 },
  { id: LAB_CUE.command, src: 'audio/cue_command.wav', bus: 'sfx', volume: 0.45, cooldownMs: 800 },
  { id: LAB_CUE.success, src: 'audio/cue_success.wav', bus: 'sfx', volume: 0.45, cooldownMs: 800 },
  { id: LAB_CUE.fail, src: 'audio/cue_fail.wav', bus: 'sfx', volume: 0.45, cooldownMs: 800 },
  // track loss can flap - at most one "signal lost" blip every few seconds
  { id: LAB_CUE.trackLost, src: 'audio/cue_track_lost.wav', bus: 'sfx', volume: 0.35, cooldownMs: 5000 },
];
